### ISSUE TITLE
thêm và update dòng dịch

### ISSUE THREAD

**Issue by DangNgocThao** [Sang5231/RP-Vietnamese#1]
tôi thấy bạn thiếu những dòng này
structure_block.import=Nhập
hbui.Achievements.notAvailableMessage=Bạn chỉ có thể đạt được các thành tựu trong phiên bản chính thức của Minecraft.
hbui.Achievements.notAvailableMessageTitle=Thành tựu không khả dụng trong Phiên bản Preview
và update lại những chỗ này
store.search.sort_menu.HighestPrice=Giá: cao -> thấp
store.search.sort_menu.LowestPrice=Giá: thấp -> cao
enchantment.lootBonusFishing=Sự may mắn của đại dương

**Comment by Sang5231** [comment]
Thank bạn, tui sẽ thêm nó từ từ vào các bản cập nhật sau!!!

**Comment by DangNgocThao** [comment]
bạn copy bị lỗi như này enchantment.lootBonusFishing=enchantment.lootBonusFishing=Sự may mắn của đại dương
cái nó thành như này r
![Ảnh chụp màn hình 2024-04-08 232020](https://github.com/Sang5231/RP-Vietnamese/assets/125102727/3acbbc63-678c-4b13-a9d6-ce9f7e8560ed)

**Comment by Sang5231** [comment]
Đã fix ở bản Pre-Release của 1.21 và đợi tới 1.20.80 sẽ sửa lại luôn
