### ISSUE TITLE
bổ sung bản dịch cho realms stories

### ISSUE THREAD

**Issue by DangNgocThao** [Sang5231/RP-Vietnamese#2]
bản v1.21 Pre-Release 3 trong giao diện minecraft của tôi thì còn những dòng này chưa dịch
và đây là bổ sung:

hbui.RealmsStories.members.allMembers=Tất cả thành viên
hbui.RealmsStories.members.onlineMembers=Thành viên trực tuyến
hbui.RealmsStories.settings.realmWideSettings.storyCoordinates.title=Toạ độ Sự kiện Realm
hbui.RealmsStories.settings.realmWideSettings.storyCoordinates.description=Hiển thị toạ độ cho một số Sự kiện Realm cụ thể, nếu cài đặt "Hiển thị toạ độ" của thế giới được bật khi các sự kiện được kích hoạt.

**Comment by Sang5231** [comment]
Cảm ơn đóng góp của bạn
Nhiều khi tui cũng dịch sót nhiều chỗ

**Comment by DangNgocThao** [comment]
trong bản preview có thêm chức năng hiện số ngày đã chơi vẫn còn thiếu bản dịch khi vô game
và đây là bổ sung:

hudScreen.daysPlayed=Số ngày đã chơi: %s
hudScreen.daysPlayed.overflow=Quá nhiều để đếm!

**Comment by DangNgocThao** [comment]
trong phần addon có dòng

tesourcePack.warning.add.title=Cập nhật thế giới?

bị sai từ khóa chữ t ở đầu dòng phải sửa lại thành từ r
và đây là dòng đúng

resourcePack.warning.add.title=Cập nhật thế giới?

và ở đây bổ sung thêm những dòng bị thiếu của phần addon:

resourcePack.warning.add.button.cancel=Không thêm gói
resourcePack.warning.add.button.ok=Vẫn thêm gói
resourcePack.warnings.contentKeyErrorBody=Có sự cố khi tải gói %s.
resourcePack.warnings.contentKeyErrorBodyMultiple=Có sự cố khi tải gói %s.
resourcePack.warnings.contentKeyErrorTitle=Lỗi!
resourcePack.warning.remove.title=Điều Này Rất Nguy Hiểm!
resourcePack.warning.remove.body=Thêm hoặc loại bỏ các Gói sau khi chơi một thế giới có thể làm hỏng thế giới và khiến bạn mất những gì bạn đã tạo ra.
resourcePack.warning.remove.button.cancel=Giữ gói
resourcePack.warning.remove.button.ok=Vẫn xóa gói
