### ISSUE TITLE
sửa lỗi bản dịch

### ISSUE THREAD

**Issue by DangNgocThao** [Sang5231/RP-Vietnamese#4]
### v1.21 Tricky Trials Update
cập nhật lại những dòng này:

1. sai chữ cái đầu chữ "t" thành "r"

❌
tesourcePack.warning.add.title=Cập nhật thế giới?

➜
resourcePack.warning.add.title=Cập nhật thế giới?

2. thiếu title trong khi đó lại có đến tận 2 body

❌
resourcePack.warning.remove.body=Thêm hoặc xóa Gói sau khi chơi một thế giới có thể phá vỡ thế giới đó và khiến bạn mất đi những gì bạn đã tạo.

➜
resourcePack.warning.remove.title=Điều Này Rất Nguy Hiểm!

3. thiếu ".remove" ở giữa trên ".body"

❌
resourcePack.warning.body=Thêm hoặc xóa các gói hành vi sau khi chơi một thế giới có thể phá vỡ thế giới và khiến bạn mất những gì bạn đã tạo.	#

➜
resourcePack.warning.remove.body=Thêm hoặc xóa các gói hành vi sau khi chơi một thế giới có thể phá vỡ thế giới và khiến bạn mất những gì bạn đã tạo.	#

4. dư " (%1$s)"

❌
hbui.AddFriendAccordion.recentlyPlayedWith=Được chơi gần đây (%1$s)

➜
hbui.AddFriendAccordion.recentlyPlayedWith=Được chơi gần đây

5. sai từ "Môca" thành "Mốc"

❌
hbui.RealmsStories.messages.timelineEmpty.body=Chơi trên Realm để tạo dữ liệu Môca thời gian.

➜
hbui.RealmsStories.messages.timelineEmpty.body=Chơi trên Realm để tạo dữ liệu Mốc thời gian.

6. chuyển "storyCoordines" thành "storyCoordinates"

❌
hbui.RealmsStories.settings.realmWideSettings.storyCoordines.description=Hiển thị tọa độ cho một số Sự kiện Realm nhất định, nếu cài đặt "Hiển thị tọa độ" của thế giới được bật khi sự kiện được kích hoạt.

➜
hbui.RealmsStories.settings.realmWideSettings.storyCoordinates.description=Hiển thị tọa độ cho một số Sự kiện Realm nhất định, nếu cài đặt "Hiển thị tọa độ" của thế giới được bật khi sự kiện được kích hoạt.

7. tương tự trên chuyển "storyCoordines" thành "storyCoordinates"

❌
hbui.RealmsStories.settings.realmWideSettings.storyCoordines.title=Tọa độ sự kiện Realm

➜
hbui.RealmsStories.settings.realmWideSettings.storyCoordinates.title=Tọa độ sự kiện Realm

8. thêm dòng này cho bản dịch thêm bạn bè

➜
hbui.AddFriendAccordion.recommendedFriends=Bạn bè được đề xuất

### v1.21.10 Pre-Release 3
cập nhật lại những dòng này tương tự "v1.21 Tricky Trials Update":

1. thiếu ".remove" ở giữa trên ".body"

❌
resourcePack.warning.body=Thêm hoặc xóa các gói hành vi sau khi chơi một thế giới có thể phá vỡ thế giới và khiến bạn mất những gì bạn đã tạo.	#

➜
resourcePack.warning.remove.body=Thêm hoặc xóa các gói hành vi sau khi chơi một thế giới có thể phá vỡ thế giới và khiến bạn mất những gì bạn đã tạo.	#

2. sai từ "Môca" thành "Mốc"

❌
hbui.RealmsStories.messages.timelineEmpty.body=Chơi trên Realm để tạo dữ liệu Môca thời gian.

➜
hbui.RealmsStories.messages.timelineEmpty.body=Chơi trên Realm để tạo dữ liệu Mốc thời gian.

3. thêm dòng này cho bản dịch thêm bạn bè tương tự "v1.21 Tricky Trials Update"

➜
hbui.AddFriendAccordion.recommendedFriends=Bạn bè được đề xuất

tôi thấy 2 bản dịch cho bản preview và bản chính thức không được đồng bộ cho lắm
trong khi bản dịch bên bản preview dịch khá tốt ít lỗi hơn bản chính thức
nếu bạn có sài **Visual Studio Code** bạn có thể sử dụng tiện ích **Select Compare Tabs** để coi sự khác biệt giữa 2 bản
![Ảnh chụp màn hình 2024-06-18 031519](https://github.com/Sang5231/RP-Vietnamese/assets/125102727/c3e00d4a-7ac9-492b-8b55-6b775032ae1f)

**Comment by Sang5231** [comment]
Cảm ơn bạn rất nhều!!!

**Comment by Sang5231** [comment]
Riêng bản Preview lỗi ở Preview 1.21.10.Pre3 sẽ sửa ở Pre4
